version: "3.7"
services:
  react-app:
    image: product-feedback-app
    stdin_open: true
    ports:
      - "3000:3000"
  api-server:
    image: product-feedback-api
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
